"use client";

import React, { useState, useEffect } from "react";
import {
  CheckSquare,
  Plus,
  Search,
  Sparkles,
  Loader2,
} from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Badge } from "@/components/ui/Badge";
import { Avatar } from "@/components/ui/Avatar";
import { Modal } from "@/components/ui/Modal";
import { TableSkeleton } from "@/components/ui/Skeleton";

export default function TasksPage() {
  const [tasks, setTasks] = useState<any[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [members, setMembers] = useState<any[]>([]);
  const [workspace, setWorkspace] = useState<any>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  // New task form state
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [projectId, setProjectId] = useState("");
  const [assigneeId, setAssigneeId] = useState("");
  const [priority, setPriority] = useState("MEDIUM");
  const [status, setStatus] = useState("TODO");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGeneratingDesc, setIsGeneratingDesc] = useState(false);

  useEffect(() => {
    loadTasksData();
  }, []);

  const loadTasksData = async () => {
    setIsLoading(true);
    try {
      const wsRes = await fetch("/api/workspaces");
      if (wsRes.ok) {
        const wsData = await wsRes.json();
        const activeWs = wsData.workspaces?.[0];
        setWorkspace(activeWs);

        if (activeWs) {
          const [tRes, pRes, mRes] = await Promise.all([
            fetch(`/api/tasks?workspaceId=${activeWs.id}`),
            fetch(`/api/projects?workspaceId=${activeWs.id}`),
            fetch(`/api/workspaces/${activeWs.id}/members`),
          ]);

          if (tRes.ok) {
            const tData = await tRes.json();
            setTasks(tData.tasks || []);
          }
          if (pRes.ok) {
            const pData = await pRes.json();
            setProjects(pData.projects || []);
            if (pData.projects?.length > 0) setProjectId(pData.projects[0].id);
          }
          if (mRes.ok) {
            const mData = await mRes.json();
            setMembers(mData.members || []);
          }
        }
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  const handleAutoGenerateDesc = async () => {
    if (!title.trim()) return;
    setIsGeneratingDesc(true);

    try {
      const res = await fetch("/api/ai/generate-description", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, type: "task" }),
      });

      const data = await res.json();
      if (res.ok && data.description) {
        setDescription(data.description);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsGeneratingDesc(false);
    }
  };

  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!workspace || !projectId || !title) return;
    setIsSubmitting(true);

    try {
      const res = await fetch("/api/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          workspaceId: workspace.id,
          projectId,
          title,
          description,
          priority,
          status,
          assigneeId: assigneeId || null,
        }),
      });

      if (res.ok) {
        setIsModalOpen(false);
        setTitle("");
        setDescription("");
        loadTasksData();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleStatusChange = async (taskId: string, newStatus: string) => {
    setTasks((prev) =>
      prev.map((t) => (t.id === taskId ? { ...t, status: newStatus } : t))
    );

    await fetch("/api/tasks", {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        taskId,
        workspaceId: workspace.id,
        status: newStatus,
      }),
    });
  };

  const filteredTasks = tasks.filter((t) => {
    const matchesSearch = t.title.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = statusFilter === "ALL" || t.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  return (
    <AppShell>
      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight flex items-center gap-2">
              <CheckSquare className="w-6 h-6 text-[#38BDF8]" />
              <span>Task Management</span>
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Search, filter, and assign tasks across your projects
            </p>
          </div>
          <Button icon={<Plus className="w-4 h-4" />} onClick={() => setIsModalOpen(true)}>
            New Task
          </Button>
        </div>

        {/* Toolbar */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 bg-white dark:bg-slate-900 p-3 rounded-[18px] border border-slate-200/80 dark:border-slate-800 shadow-sm">
          <div className="w-full sm:w-80">
            <Input
              placeholder="Search tasks..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              icon={<Search className="w-4 h-4" />}
            />
          </div>

          <div className="flex items-center gap-3">
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="bg-slate-100 dark:bg-slate-800 dark:text-slate-200 border border-transparent dark:border-slate-700 rounded-[12px] px-3 py-2 text-xs font-semibold text-slate-700 outline-none"
            >
              <option value="ALL">All Statuses</option>
              <option value="TODO">To Do</option>
              <option value="IN_PROGRESS">In Progress</option>
              <option value="REVIEW">In Review</option>
              <option value="DONE">Completed</option>
            </select>
          </div>
        </div>

        {/* Tasks Table */}
        {isLoading ? (
          <TableSkeleton rows={6} />
        ) : (
          <div className="bg-white dark:bg-slate-900 rounded-[24px] border border-slate-200/80 dark:border-slate-800 shadow-sm overflow-hidden">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/80 dark:bg-slate-800/80 border-b border-slate-100 dark:border-slate-800 text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">
                  <th className="py-3.5 px-6">Task Title</th>
                  <th className="py-3.5 px-6">Project</th>
                  <th className="py-3.5 px-6">Status</th>
                  <th className="py-3.5 px-6">Priority</th>
                  <th className="py-3.5 px-6">Assignee</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800 text-xs">
                {filteredTasks.map((t) => (
                  <tr key={t.id} className="hover:bg-slate-50/60 dark:hover:bg-slate-800/60 transition-colors">
                    <td className="py-4 px-6 font-bold text-slate-900 dark:text-white">{t.title}</td>
                    <td className="py-4 px-6">
                      <span className="font-semibold text-slate-600 dark:text-slate-400">{t.project?.name || "Project"}</span>
                    </td>
                    <td className="py-4 px-6">
                      <select
                        value={t.status}
                        onChange={(e) => handleStatusChange(t.id, e.target.value)}
                        className={`px-2.5 py-1 rounded-full text-[11px] font-bold outline-none cursor-pointer ${
                          t.status === "DONE"
                            ? "bg-emerald-100 text-emerald-700"
                            : t.status === "IN_PROGRESS"
                            ? "bg-[#E0F2FE] text-[#0284C7]"
                            : "bg-amber-100 text-amber-700"
                        }`}
                      >
                        <option value="TODO">To Do</option>
                        <option value="IN_PROGRESS">In Progress</option>
                        <option value="REVIEW">In Review</option>
                        <option value="DONE">Done</option>
                      </select>
                    </td>
                    <td className="py-4 px-6">
                      <Badge variant={t.priority === "URGENT" ? "danger" : "purple"} size="sm">
                        {t.priority}
                      </Badge>
                    </td>
                    <td className="py-4 px-6">
                      {t.assignee ? (
                        <div className="flex items-center gap-2">
                          <Avatar name={t.assignee.name} src={t.assignee.avatarUrl} size="sm" />
                          <span className="font-medium text-slate-700 dark:text-slate-300">{t.assignee.name}</span>
                        </div>
                      ) : (
                        <span className="text-slate-400 dark:text-slate-500 font-medium">Unassigned</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Create Task Modal */}
        <Modal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          title="Create New Task"
          subtitle="Add a new task to your sprint"
        >
          <form onSubmit={handleCreateTask} className="space-y-4">
            <Input
              label="Task Title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Build Auth API endpoint"
              required
            />

            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Project</label>
              <select
                value={projectId}
                onChange={(e) => setProjectId(e.target.value)}
                className="w-full bg-slate-100/80 dark:bg-slate-800 dark:text-slate-100 border border-transparent dark:border-slate-700 rounded-[12px] p-3 text-sm focus:bg-white dark:focus:bg-slate-900 focus:border-[#38BDF8] outline-none"
              >
                {projects.map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.name} ({p.key})
                  </option>
                ))}
              </select>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Priority</label>
                <select
                  value={priority}
                  onChange={(e) => setPriority(e.target.value)}
                  className="w-full bg-slate-100/80 dark:bg-slate-800 dark:text-slate-100 border border-transparent dark:border-slate-700 rounded-[12px] p-3 text-sm focus:bg-white dark:focus:bg-slate-900 focus:border-[#38BDF8] outline-none"
                >
                  <option value="LOW">Low</option>
                  <option value="MEDIUM">Medium</option>
                  <option value="HIGH">High</option>
                  <option value="URGENT">Urgent</option>
                </select>
              </div>

              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Assignee</label>
                <select
                  value={assigneeId}
                  onChange={(e) => setAssigneeId(e.target.value)}
                  className="w-full bg-slate-100/80 dark:bg-slate-800 dark:text-slate-100 border border-transparent dark:border-slate-700 rounded-[12px] p-3 text-sm focus:bg-white dark:focus:bg-slate-900 focus:border-[#38BDF8] outline-none"
                >
                  <option value="">Unassigned</option>
                  {members.map((m) => (
                    <option key={m.user.id} value={m.user.id}>
                      {m.user.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="flex flex-col gap-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Description</label>
                <button
                  type="button"
                  onClick={handleAutoGenerateDesc}
                  disabled={!title.trim() || isGeneratingDesc}
                  className="text-[11px] font-bold text-[#38BDF8] hover:underline flex items-center gap-1 disabled:opacity-40 disabled:no-underline cursor-pointer"
                >
                  {isGeneratingDesc ? (
                    <Loader2 className="w-3 h-3 animate-spin text-[#38BDF8]" />
                  ) : (
                    <Sparkles className="w-3 h-3 text-[#38BDF8]" />
                  )}
                  <span>Auto-Generate Description</span>
                </button>
              </div>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Task criteria and details..."
                className="w-full bg-slate-100/80 dark:bg-slate-800 dark:text-slate-100 border border-transparent dark:border-slate-700 rounded-[12px] p-3 text-sm focus:bg-white dark:focus:bg-slate-900 focus:border-[#38BDF8] outline-none"
                rows={3}
              />
            </div>

            <div className="pt-3 flex items-center justify-end gap-3">
              <Button type="button" variant="secondary" onClick={() => setIsModalOpen(false)}>
                Cancel
              </Button>
              <Button type="submit" isLoading={isSubmitting}>
                Create Task
              </Button>
            </div>
          </form>
        </Modal>
      </div>
    </AppShell>
  );
}
