"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import {
  Plus,
  Search,
  LayoutGrid,
  List as ListIcon,
  CheckCircle2,
  Sparkles,
  Loader2,
} from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { Badge } from "@/components/ui/Badge";
import { AvatarGroup } from "@/components/ui/Avatar";
import { Tabs } from "@/components/ui/Tabs";
import { CardSkeleton, TableSkeleton } from "@/components/ui/Skeleton";

export default function ProjectsPage() {
  const [projects, setProjects] = useState<any[]>([]);
  const [workspace, setWorkspace] = useState<any>(null);
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");
  const [searchQuery, setSearchQuery] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  // New project form state
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [key, setKey] = useState("");
  const [color, setColor] = useState("#635BFF");
  const [deadline, setDeadline] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGeneratingDesc, setIsGeneratingDesc] = useState(false);

  useEffect(() => {
    loadProjects();
  }, []);

  const loadProjects = async () => {
    setIsLoading(true);
    try {
      const wsRes = await fetch("/api/workspaces");
      if (wsRes.ok) {
        const wsData = await wsRes.json();
        const activeWs = wsData.workspaces?.[0];
        setWorkspace(activeWs);

        if (activeWs) {
          const projRes = await fetch(`/api/projects?workspaceId=${activeWs.id}`);
          if (projRes.ok) {
            const pData = await projRes.json();
            setProjects(pData.projects || []);
          }
        }
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  const handleAutoGenerateDesc = async () => {
    if (!name.trim()) return;
    setIsGeneratingDesc(true);

    try {
      const res = await fetch("/api/ai/generate-description", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: name, type: "project" }),
      });

      const data = await res.json();
      if (res.ok && data.description) {
        setDescription(data.description);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsGeneratingDesc(false);
    }
  };

  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!workspace) return;
    setIsSubmitting(true);

    try {
      const res = await fetch("/api/projects", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          workspaceId: workspace.id,
          name,
          description,
          key: key || name.substring(0, 3).toUpperCase(),
          color,
          deadline: deadline || null,
        }),
      });

      if (res.ok) {
        setIsModalOpen(false);
        setName("");
        setDescription("");
        setKey("");
        loadProjects();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsSubmitting(false);
    }
  };

  const filteredProjects = projects.filter((p) =>
    p.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <AppShell>
      <div className="space-y-6">
        {/* Header bar */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">Projects</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Manage active workspace projects and sprints</p>
          </div>
          <Button icon={<Plus className="w-4 h-4" />} onClick={() => setIsModalOpen(true)}>
            Create Project
          </Button>
        </div>

        {/* Filter and Controls Toolbar */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 bg-white dark:bg-slate-900 p-3 rounded-[18px] border border-slate-200/80 dark:border-slate-800 shadow-sm">
          <div className="w-full sm:w-80">
            <Input
              placeholder="Search projects..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              icon={<Search className="w-4 h-4" />}
            />
          </div>

          <div className="flex items-center gap-2">
            <Tabs
              tabs={[
                { id: "grid", label: "Grid", icon: <LayoutGrid className="w-3.5 h-3.5" /> },
                { id: "list", label: "List", icon: <ListIcon className="w-3.5 h-3.5" /> },
              ]}
              activeTab={viewMode}
              onChange={(id) => setViewMode(id as "grid" | "list")}
            />
          </div>
        </div>

        {/* Projects View */}
        {isLoading ? (
          viewMode === "grid" ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <CardSkeleton />
              <CardSkeleton />
              <CardSkeleton />
            </div>
          ) : (
            <TableSkeleton />
          )
        ) : viewMode === "grid" ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredProjects.map((p) => {
              const totalTasks = p.tasks?.length || 0;
              const doneTasks = p.tasks?.filter((t: any) => t.status === "DONE").length || 0;
              const progress = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;

              return (
                <Link key={p.id} href={`/projects/${p.id}`} className="group block">
                  <div className="p-6 rounded-[24px] bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm hover:shadow-xl hover:border-slate-300 dark:hover:border-[#38BDF8] transition-all duration-200 flex flex-col justify-between h-full">
                    <div>
                      <div className="flex items-center justify-between mb-4">
                        <div
                          className="w-11 h-11 rounded-[14px] flex items-center justify-center font-extrabold text-white text-sm shadow-md"
                          style={{ backgroundColor: p.color || "#635BFF" }}
                        >
                          {p.key || p.name.substring(0, 2).toUpperCase()}
                        </div>
                        <Badge variant="purple">Active</Badge>
                      </div>

                      <h3 className="text-lg font-bold text-slate-900 dark:text-white group-hover:text-[#38BDF8] transition-colors">
                        {p.name}
                      </h3>
                      <p className="text-xs text-slate-500 dark:text-slate-400 mt-1.5 line-clamp-2 leading-relaxed">
                        {p.description || "No description provided."}
                      </p>
                    </div>

                    <div className="mt-6 pt-4 border-t border-slate-100 dark:border-slate-800 space-y-3">
                      <div>
                        <div className="flex items-center justify-between text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">
                          <span>Progress</span>
                          <span>{progress}%</span>
                        </div>
                        <div className="w-full h-2 rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden">
                          <div
                            className="h-full rounded-full transition-all duration-500"
                            style={{ width: `${progress}%`, backgroundColor: p.color || "#635BFF" }}
                          />
                        </div>
                      </div>

                      <div className="flex items-center justify-between text-xs text-slate-500 dark:text-slate-400 pt-1">
                        <div className="flex items-center gap-1.5">
                          <CheckCircle2 className="w-3.5 h-3.5 text-slate-400" />
                          <span>{doneTasks}/{totalTasks} Tasks</span>
                        </div>
                        <AvatarGroup users={p.members?.map((m: any) => m.user) || []} max={3} />
                      </div>
                    </div>
                  </div>
                </Link>
              );
            })}
          </div>
        ) : (
          <div className="bg-white dark:bg-slate-900 rounded-[24px] border border-slate-200/80 dark:border-slate-800 shadow-sm overflow-hidden">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/80 dark:bg-slate-800/80 border-b border-slate-100 dark:border-slate-800 text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">
                  <th className="py-3.5 px-6">Project Name</th>
                  <th className="py-3.5 px-6">Key</th>
                  <th className="py-3.5 px-6">Tasks</th>
                  <th className="py-3.5 px-6">Progress</th>
                  <th className="py-3.5 px-6">Members</th>
                  <th className="py-3.5 px-6">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800 text-xs">
                {filteredProjects.map((p) => {
                  const totalTasks = p.tasks?.length || 0;
                  const doneTasks = p.tasks?.filter((t: any) => t.status === "DONE").length || 0;
                  const progress = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;

                  return (
                    <tr key={p.id} className="hover:bg-slate-50/60 dark:hover:bg-slate-800/60 transition-colors">
                      <td className="py-4 px-6 font-bold text-slate-900 dark:text-white">
                        <Link href={`/projects/${p.id}`} className="hover:text-[#38BDF8]">
                          {p.name}
                        </Link>
                      </td>
                      <td className="py-4 px-6 font-mono font-semibold text-slate-500 dark:text-slate-400">{p.key}</td>
                      <td className="py-4 px-6 font-medium text-slate-600 dark:text-slate-400">{doneTasks}/{totalTasks}</td>
                      <td className="py-4 px-6">
                        <span className="font-bold text-slate-900 dark:text-white">{progress}%</span>
                      </td>
                      <td className="py-4 px-6">
                        <AvatarGroup users={p.members?.map((m: any) => m.user) || []} max={3} />
                      </td>
                      <td className="py-4 px-6">
                        <Badge variant="purple">Active</Badge>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {/* Create Project Modal */}
        <Modal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          title="Create New Project"
          subtitle="Add a new project to your workspace"
        >
          <form onSubmit={handleCreateProject} className="space-y-4">
            <Input
              label="Project Name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Mobile Application Redesign"
              required
            />

            <div className="grid grid-cols-2 gap-4">
              <Input
                label="Project Key (3 letters)"
                value={key}
                onChange={(e) => setKey(e.target.value.toUpperCase())}
                placeholder="MOB"
              />

              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Accent Color</label>
                <div className="flex items-center gap-2">
                  <input
                    type="color"
                    value={color}
                    onChange={(e) => setColor(e.target.value)}
                    className="w-9 h-9 rounded-[10px] cursor-pointer border-0"
                  />
                  <span className="text-xs font-mono text-slate-600 dark:text-slate-400">{color}</span>
                </div>
              </div>
            </div>

            <div className="flex flex-col gap-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Description</label>
                <button
                  type="button"
                  onClick={handleAutoGenerateDesc}
                  disabled={!name.trim() || isGeneratingDesc}
                  className="text-[11px] font-bold text-[#38BDF8] hover:underline flex items-center gap-1 disabled:opacity-40 disabled:no-underline cursor-pointer"
                >
                  {isGeneratingDesc ? (
                    <Loader2 className="w-3 h-3 animate-spin text-[#38BDF8]" />
                  ) : (
                    <Sparkles className="w-3 h-3 text-[#38BDF8]" />
                  )}
                  <span>Auto-Generate Description</span>
                </button>
              </div>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Briefly describe project objectives or click Auto-Generate..."
                className="w-full bg-slate-100/80 dark:bg-slate-800 dark:text-slate-100 border border-transparent dark:border-slate-700 rounded-[12px] p-3 text-sm focus:bg-white dark:focus:bg-slate-900 focus:border-[#38BDF8] outline-none"
                rows={3}
              />
            </div>

            <Input
              label="Deadline (Optional)"
              type="date"
              value={deadline}
              onChange={(e) => setDeadline(e.target.value)}
            />

            <div className="pt-3 flex items-center justify-end gap-3">
              <Button type="button" variant="secondary" onClick={() => setIsModalOpen(false)}>
                Cancel
              </Button>
              <Button type="submit" isLoading={isSubmitting}>
                Create Project
              </Button>
            </div>
          </form>
        </Modal>
      </div>
    </AppShell>
  );
}
