"use client";

import React, { useState, useEffect, use } from "react";
import Link from "next/link";
import {
  FolderKanban,
  CheckCircle2,
  Clock,
  Users,
  Calendar,
  ArrowLeft,
  Plus,
  MessageSquare,
  Sparkles,
  Loader2,
} from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Badge } from "@/components/ui/Badge";
import { Avatar } from "@/components/ui/Avatar";
import { Button } from "@/components/ui/Button";
import { Tabs } from "@/components/ui/Tabs";
import { Modal } from "@/components/ui/Modal";
import { Input } from "@/components/ui/Input";

export default function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id: projectId } = use(params);

  const [project, setProject] = useState<any>(null);
  const [tasks, setTasks] = useState<any[]>([]);
  const [members, setMembers] = useState<any[]>([]);
  const [workspace, setWorkspace] = useState<any>(null);
  const [activeTab, setActiveTab] = useState("overview");
  const [isModalOpen, setIsModalOpen] = useState(false);

  // New task form state
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [assigneeId, setAssigneeId] = useState("");
  const [priority, setPriority] = useState("MEDIUM");
  const [status, setStatus] = useState("TODO");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGeneratingDesc, setIsGeneratingDesc] = useState(false);

  useEffect(() => {
    loadProjectDetails();
  }, [projectId]);

  const loadProjectDetails = async () => {
    try {
      const wsRes = await fetch("/api/workspaces");
      if (wsRes.ok) {
        const wsData = await wsRes.json();
        const activeWs = wsData.workspaces?.[0];
        setWorkspace(activeWs);

        if (activeWs) {
          const projRes = await fetch(`/api/projects?workspaceId=${activeWs.id}`);
          if (projRes.ok) {
            const pData = await projRes.json();
            const found = pData.projects?.find((p: any) => p.id === projectId);
            setProject(found);
          }

          const [taskRes, mRes] = await Promise.all([
            fetch(`/api/tasks?workspaceId=${activeWs.id}&projectId=${projectId}`),
            fetch(`/api/workspaces/${activeWs.id}/members`),
          ]);

          if (taskRes.ok) {
            const tData = await taskRes.json();
            setTasks(tData.tasks || []);
          }
          if (mRes.ok) {
            const mData = await mRes.json();
            setMembers(mData.members || []);
          }
        }
      }
    } catch (e) {
      console.error(e);
    }
  };

  const handleAutoGenerateDesc = async () => {
    if (!title.trim()) return;
    setIsGeneratingDesc(true);

    try {
      const res = await fetch("/api/ai/generate-description", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, type: "task" }),
      });

      const data = await res.json();
      if (res.ok && data.description) {
        setDescription(data.description);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsGeneratingDesc(false);
    }
  };

  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!workspace || !title) return;
    setIsSubmitting(true);

    try {
      const res = await fetch("/api/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          workspaceId: workspace.id,
          projectId,
          title,
          description,
          priority,
          status,
          assigneeId: assigneeId || null,
        }),
      });

      if (res.ok) {
        setIsModalOpen(false);
        setTitle("");
        setDescription("");
        loadProjectDetails();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!project) {
    return (
      <AppShell>
        <div className="py-20 text-center text-slate-500 dark:text-slate-400">Loading project details...</div>
      </AppShell>
    );
  }

  const completedCount = tasks.filter((t) => t.status === "DONE").length;
  const progress = tasks.length > 0 ? Math.round((completedCount / tasks.length) * 100) : 0;

  return (
    <AppShell>
      <div className="space-y-6">
        {/* Back button */}
        <Link
          href="/projects"
          className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Projects</span>
        </Link>

        {/* Project Header Banner */}
        <div className="p-8 rounded-[28px] bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div
              className="w-16 h-16 rounded-[20px] flex items-center justify-center font-black text-white text-2xl shadow-lg"
              style={{ backgroundColor: project.color || "#38BDF8" }}
            >
              {project.key}
            </div>
            <div>
              <div className="flex items-center gap-3">
                <h2 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">
                  {project.name}
                </h2>
                <Badge variant="purple">Active</Badge>
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-xl">
                {project.description || "Project workspace overview and sprint tracking."}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <Button icon={<Plus className="w-4 h-4" />} onClick={() => setIsModalOpen(true)}>
              Add Task to Project
            </Button>
            <Link href="/kanban">
              <Button variant="secondary" icon={<FolderKanban className="w-4 h-4" />}>
                Kanban Board
              </Button>
            </Link>
          </div>
        </div>

        {/* Project Navigation Tabs */}
        <Tabs
          tabs={[
            { id: "overview", label: "Overview" },
            { id: "tasks", label: "Tasks", count: tasks.length },
            { id: "team", label: "Team", count: members.length },
          ]}
          activeTab={activeTab}
          onChange={setActiveTab}
        />

        {/* Tab 1: Overview */}
        {activeTab === "overview" && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Left overview cards */}
            <div className="lg:col-span-2 space-y-6">
              <div className="p-6 rounded-[24px] bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm">
                <h3 className="font-bold text-slate-900 dark:text-white text-base mb-4">Completion Status</h3>
                <div className="flex items-center justify-between text-xs font-semibold text-slate-600 dark:text-slate-400 mb-2">
                  <span>Overall Milestone Progress</span>
                  <span className="font-extrabold text-[#38BDF8]">{progress}%</span>
                </div>
                <div className="w-full h-3 rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-[#38BDF8] to-[#2563EB] transition-all duration-500"
                    style={{ width: `${progress}%` }}
                  />
                </div>

                <div className="grid grid-cols-3 gap-4 mt-6 text-center">
                  <div className="p-4 rounded-[16px] bg-slate-50 dark:bg-slate-800 border border-slate-100 dark:border-slate-700">
                    <span className="text-2xl font-extrabold text-slate-900 dark:text-white block">{tasks.length}</span>
                    <span className="text-[11px] text-slate-500 dark:text-slate-400">Total Tasks</span>
                  </div>
                  <div className="p-4 rounded-[16px] bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-100 dark:border-emerald-800/50">
                    <span className="text-2xl font-extrabold text-emerald-700 dark:text-emerald-400 block">{completedCount}</span>
                    <span className="text-[11px] text-emerald-600 dark:text-emerald-500">Completed</span>
                  </div>
                  <div className="p-4 rounded-[16px] bg-amber-50 dark:bg-amber-950/30 border border-amber-100 dark:border-amber-800/50">
                    <span className="text-2xl font-extrabold text-amber-700 dark:text-amber-400 block">
                      {tasks.length - completedCount}
                    </span>
                    <span className="text-[11px] text-amber-600 dark:text-amber-500">Remaining</span>
                  </div>
                </div>
              </div>

              {/* Task list preview */}
              <div className="p-6 rounded-[24px] bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-bold text-slate-900 dark:text-white text-base">Project Tasks Preview</h3>
                  <button
                    onClick={() => setIsModalOpen(true)}
                    className="text-xs font-bold text-[#38BDF8] hover:underline flex items-center gap-1"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Split Work into New Task</span>
                  </button>
                </div>
                <div className="space-y-3">
                  {tasks.length === 0 ? (
                    <p className="text-xs text-slate-400 dark:text-slate-500 py-6 text-center">
                      No tasks created for this project yet. Click "Add Task" to split work!
                    </p>
                  ) : (
                    tasks.map((t) => (
                      <div
                        key={t.id}
                        className="flex items-center justify-between p-3.5 rounded-[16px] bg-slate-50/80 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/60"
                      >
                        <div className="flex items-center gap-3">
                          <span
                            className={`w-2.5 h-2.5 rounded-full ${
                              t.status === "DONE"
                                ? "bg-emerald-500"
                                : t.status === "IN_PROGRESS"
                                ? "bg-[#38BDF8]"
                                : "bg-amber-500"
                            }`}
                          />
                          <div>
                            <span className="font-bold text-slate-900 dark:text-white text-sm block">{t.title}</span>
                            <span className="text-[11px] text-slate-500 dark:text-slate-400">
                              Assignee: {t.assignee?.name || "Unassigned"}
                            </span>
                          </div>
                        </div>
                        <Badge variant={t.priority === "URGENT" ? "danger" : "purple"} size="sm">
                          {t.priority}
                        </Badge>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>

            {/* Right sidebar */}
            <div className="space-y-6">
              <div className="p-6 rounded-[24px] bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm">
                <h3 className="font-bold text-slate-900 dark:text-white text-base mb-4">Assigned Workspace Members</h3>
                <div className="space-y-3">
                  {members.map((m: any) => (
                    <div key={m.id} className="flex items-center gap-3">
                      <Avatar name={m.user.name} src={m.user.avatarUrl} size="sm" />
                      <div>
                        <span className="font-bold text-slate-900 dark:text-white text-xs block">{m.user.name}</span>
                        <span className="text-[10px] text-slate-500 dark:text-slate-400">{m.user.email}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Tab 2: Tasks Tab Content */}
        {activeTab === "tasks" && (
          <div className="bg-white dark:bg-slate-900 rounded-[24px] border border-slate-200/80 dark:border-slate-800 p-6 shadow-sm space-y-4">
            <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-4">
              <div>
                <h3 className="font-bold text-slate-900 dark:text-white text-base">All Tasks for {project.name}</h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Manage and track project deliverables</p>
              </div>
              <Button icon={<Plus className="w-4 h-4" />} onClick={() => setIsModalOpen(true)}>
                Add Task
              </Button>
            </div>

            {tasks.length === 0 ? (
              <div className="py-16 text-center">
                <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">No tasks created for this project yet.</p>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Click "Add Task" to split work and assign team members!</p>
                <div className="mt-4">
                  <Button icon={<Plus className="w-4 h-4" />} onClick={() => setIsModalOpen(true)}>
                    Create First Task
                  </Button>
                </div>
              </div>
            ) : (
              <div className="space-y-3">
                {tasks.map((t) => (
                  <div
                    key={t.id}
                    className="flex items-center justify-between p-4 rounded-[16px] bg-slate-50/80 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/60 hover:bg-slate-100/80 dark:hover:bg-slate-800 transition-colors"
                  >
                    <div className="flex items-center gap-3">
                      <span
                        className={`w-3 h-3 rounded-full ${
                          t.status === "DONE"
                            ? "bg-emerald-500"
                            : t.status === "IN_PROGRESS"
                            ? "bg-[#38BDF8]"
                            : "bg-amber-500"
                        }`}
                      />
                      <div>
                        <span className="font-bold text-slate-900 dark:text-white text-sm block">{t.title}</span>
                        <span className="text-xs text-slate-500 dark:text-slate-400">
                          Assignee: <strong className="text-slate-700 dark:text-slate-300">{t.assignee?.name || "Unassigned"}</strong> • Status: <strong className="text-slate-700 dark:text-slate-300">{t.status}</strong>
                        </span>
                      </div>
                    </div>
                    <Badge variant={t.priority === "URGENT" ? "danger" : "purple"} size="sm">
                      {t.priority}
                    </Badge>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Tab 3: Team Tab Content */}
        {activeTab === "team" && (
          <div className="bg-white dark:bg-slate-900 rounded-[24px] border border-slate-200/80 dark:border-slate-800 p-6 shadow-sm space-y-4">
            <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-4">
              <div>
                <h3 className="font-bold text-slate-900 dark:text-white text-base">Project Team Roster</h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">Workspace team members assigned to this project</p>
              </div>
              <Link href="/team">
                <Button variant="secondary" icon={<Users className="w-4 h-4" />}>
                  Manage Workspace Team
                </Button>
              </Link>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {members.map((m: any) => (
                <div key={m.id} className="p-4 rounded-[18px] bg-slate-50/80 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/60 flex items-center gap-3">
                  <Avatar name={m.user.name} src={m.user.avatarUrl} size="md" />
                  <div>
                    <span className="font-bold text-slate-900 dark:text-white text-sm block">{m.user.name}</span>
                    <span className="text-xs text-slate-500 dark:text-slate-400 block">{m.user.email}</span>
                    <Badge variant="purple" size="sm" className="mt-1">{m.role}</Badge>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Add Task Modal */}
        <Modal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          title={`Add Task to ${project.name}`}
          subtitle="Split project work into actionable tasks and assign team members"
        >
          <form onSubmit={handleCreateTask} className="space-y-4">
            <Input
              label="Task Title / Deliverable"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Implement User Authentication Screens"
              required
            />

            <div className="grid grid-cols-2 gap-4">
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Assignee</label>
                <select
                  value={assigneeId}
                  onChange={(e) => setAssigneeId(e.target.value)}
                  className="w-full bg-slate-100/80 dark:bg-slate-800 dark:text-slate-100 border border-transparent dark:border-slate-700 rounded-[12px] p-3 text-sm focus:bg-white dark:focus:bg-slate-900 focus:border-[#38BDF8] outline-none"
                >
                  <option value="">Unassigned</option>
                  {members.map((m) => (
                    <option key={m.user.id} value={m.user.id}>
                      {m.user.name} ({m.role})
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Priority</label>
                <select
                  value={priority}
                  onChange={(e) => setPriority(e.target.value)}
                  className="w-full bg-slate-100/80 dark:bg-slate-800 dark:text-slate-100 border border-transparent dark:border-slate-700 rounded-[12px] p-3 text-sm focus:bg-white dark:focus:bg-slate-900 focus:border-[#38BDF8] outline-none"
                >
                  <option value="LOW">Low</option>
                  <option value="MEDIUM">Medium</option>
                  <option value="HIGH">High</option>
                  <option value="URGENT">Urgent</option>
                </select>
              </div>
            </div>

            <div className="flex flex-col gap-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-slate-700 dark:text-slate-300 uppercase">Description / Details</label>
                <button
                  type="button"
                  onClick={handleAutoGenerateDesc}
                  disabled={!title.trim() || isGeneratingDesc}
                  className="text-[11px] font-bold text-[#38BDF8] hover:underline flex items-center gap-1 disabled:opacity-40 disabled:no-underline cursor-pointer"
                >
                  {isGeneratingDesc ? (
                    <Loader2 className="w-3 h-3 animate-spin text-[#38BDF8]" />
                  ) : (
                    <Sparkles className="w-3 h-3 text-[#38BDF8]" />
                  )}
                  <span>Auto-Generate Description</span>
                </button>
              </div>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Detail technical requirements or click Auto-Generate..."
                className="w-full bg-slate-100/80 dark:bg-slate-800 dark:text-slate-100 border border-transparent dark:border-slate-700 rounded-[12px] p-3 text-sm focus:bg-white dark:focus:bg-slate-900 focus:border-[#38BDF8] outline-none"
                rows={3}
              />
            </div>

            <div className="pt-3 flex items-center justify-end gap-3">
              <Button type="button" variant="secondary" onClick={() => setIsModalOpen(false)}>
                Cancel
              </Button>
              <Button type="submit" isLoading={isSubmitting}>
                Create & Assign Task
              </Button>
            </div>
          </form>
        </Modal>
      </div>
    </AppShell>
  );
}
